### ISSUE TITLE
add failing test from state to .is tests

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/is#5]
(is has nothing todo with state except that is injected by default)
remove the branch from state as soon as this is done ofc

**Comment by jimdebeer** [comment]
probably a problem with inherited listener that exists in state will try to reproduce here

**Comment by boitewitte** [comment]
Tests are now in:
`vigour-io/is` - `test/index.js`

Executed both on `observable` & `state`.

I've ran `tl` this morning and now it seems to work

**Comment by jimdebeer** [comment]
linking issue with stamp
